version: '3.8'
services:
  cache:
    image: redis:7-alpine
    restart: always
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - cache:/data
  # Service for development stage
  cache-interface:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: local:cache:${REDIS_PORT}:0:${REDIS_PASSWORD}
    ports:
      - 8081:8081
volumes:
  cache:
    driver: local
